/// Represents the entire base instruction set of the Chip8 interpreter.
#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Token {
    CLS,
    RET,
    JP_NNN(u16),
    CALL_Addr(u16),
    SE_Vx_Byte(u8, u8),
    SNE_Vx_Byte(u8, u8),
    SE_Vx_Vy(u8, u8),
    LD_Vx_Byte(u8, u8),
    ADD_Vx_Byte(u8, u8),
    LD_Vx_Vy(u8, u8),
    OR_Vx_Vy(u8, u8),
    AND_Vx_Vy(u8, u8),
    XOR_Vx_Vy(u8, u8),
    ADD_Vx_Vy(u8, u8),
    SUB_Vx_Vy(u8, u8),
    SHR_Vx_Vy(u8, u8),
    SUBN_Vx_Vy(u8, u8),
    SHL_Vx_Vy(u8, u8),
    SNE_Vx_Vy(u8, u8),
    LD_I_Addr(u16),
    JP_V0_Addr(u16),
    RND_Vx_Byte(u8, u8),
    DRW_Vx_Vy_N(u8, u8, u8),
    SKP_Vx(u8),
    SKNP_Vx(u8),
    LD_Vx_Dt(u8),
    LD_Vx_K(u8),
    LD_Dt_Vx(u8),
    LD_St_Vx(u8),
    ADD_I_Vx(u8),
    LD_F_Vx(u8),
    LD_B_Vx(u8),
    LD_I_Vx(u8),
    LD_Vx_I(u8),
    DATA(u16),
}
